name: Deploy or Destroy Azure Infrastructure

on:
  push:
    branches:
      - staging-branch
  workflow_dispatch:
    inputs:
      action:
        description: 'Destroy the resources'
        required: true
        default: 'destroy'

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -var-file=cvnet.tfvars -auto-approve

