name: Deploy Azure Infrastructure
# build or destroy
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (apply or destroy)'
        required: true
        default: 'apply'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    if: github.event.inputs.action == 'apply' || github.event_name == 'push'
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var-file=cvnet.tfvars

    - name: Terraform Apply
      run: terraform apply -var-file=cvnet.tfvars -auto-approve

  destroy:
    runs-on: ubuntu-latest
    environment: production
    if: github.event.inputs.action == 'destroy'
    needs: build
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'

    - name: Terraform Init
      run: terraform init

    - name: Terraform Destroy
      run: terraform destroy -var-file=cvnet.tfvars -auto-approve
